version: '3'
services:
  web:
    build: .
    command: --host 127.0.0.1 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://user:pass@postgres/shortener"
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shortener
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
