services:
  web:
    build: .
    command: --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URI: "postgresql://user:pass@postgres/shortener"
      HOSTNAME: "http://127.0.0.1:8000/"
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shortener
    # Uncomment for persistent database after bringing down postgres container.
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
