version: '3'
services:
  web:
    build: .
    command: poetry run uvicorn shortener.app:app --host 127.0.0.1 --port 8000
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://user:pass@postgres/shortener"
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shortener
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
